inherit_from: .rubocop_todo.yml

AllCops:
  SuggestExtensions: false
  NewCops: disable
  Exclude:
    - 'bin/bundle'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - lib/tasks/auto_annotate_models.rake

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/HashSyntax:
  Enabled: false

Style/RegexpLiteral:
  EnforcedStyle: mixed

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/routes.rb'
    - 'config/environments/*'

Metrics/AbcSize:
  Enabled: false

Lint/MissingSuper:
  Enabled: false
