services:
  db:
    build:
      context: ./infra/db
      dockerfile: Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: app_test
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: user
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - rails-railway-stations-volume:/var/lib/mysql

  web:
    build:
      context: .
      dockerfile: ./infra/web/Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    ports:
      - "3000:3000"
    links:
      - db
    stdin_open: true
    tty: true

  webpacker:
    build: 
      context: .
      dockerfile: ./infra/web/Dockerfile
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    command: ./bin/webpack-dev-server
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    ports:
      - "3035:3035"

volumes:
  rails-railway-stations-volume:
  bundle: